FIND_PATH(OSGEARTH_INCLUDE_DIR osgEarth/MapNode
    HINTS
        ${OSGEARTH_BASE_DIR}
    PATH_SUFFIXES
        /include
    NO_DEFAULT_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
)

FINDLIBRARY( OSGEARTH_LIBRARY sEarth)
FINDLIBRARY( OSGEARTH_LIBRARY_DEBUG sEarthd)

FINDLIBRARY( OSGEARTHFEATURES_LIBRARY syzEarthFeatures)
FINDLIBRARY( OSGEARTHFEATURES_LIBRARY_DEBUG syzEarthFeaturesd)

FINDLIBRARY( OSGEARTHUTIL_LIBRARY syzEarthUtil )
FINDLIBRARY( OSGEARTHUTIL_LIBRARY_DEBUG syzEarthUtild)

FINDLIBRARY( OSGEARTHSYMBOLOGY_LIBRARY syzEarthSymbology )
FINDLIBRARY( OSGEARTHSYMBOLOGY_LIBRARY_DEBUG syzEarthSymbologyd)

FINDLIBRARY( OSGEARTHANNOTATION_LIBRARY syzEarthAnnotation )
FINDLIBRARY( OSGEARTHANNOTATION_LIBRARY_DEBUG syzEarthAnnotationd)