

FIND_PATH(OSG_INCLUDE_DIR osg/Node
    HINTS
        ${OSG_BASE_DIR}
    PATH_SUFFIXES
        /include
    NO_DEFAULT_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
)


FINDLIBRARY( OSG_LIBRARY syz )
FINDLIBRARY( OSG_LIBRARY_DEBUG syzd)
FINDLIBRARY( OSGDB_LIBRARY syzDB )
FINDLIBRARY( OSGDB_LIBRARY_DEBUG syzDBd )
FINDLIBRARY( OSGFX_LIBRARY syzFX )
FINDLIBRARY( OSGFX_LIBRARY_DEBUG syzFXd )
FINDLIBRARY( OSGGA_LIBRARY syzGA )
FINDLIBRARY( OSGGA_LIBRARY_DEBUG syzGAd )
FINDLIBRARY( OSGMANIPULATOR_LIBRARY syzManipulator )
FINDLIBRARY( OSGMANIPULATOR_LIBRARY_DEBUG syzManipulatord )
FINDLIBRARY( OSGPARTICLE_LIBRARY syzParticle )
FINDLIBRARY( OSGPARTICLE_LIBRARY_DEBUG syzParticled )
FINDLIBRARY( OSGSHADOW_LIBRARY syzShadow )
FINDLIBRARY( OSGSHADOW_LIBRARY_DEBUG syzShadowd )
FINDLIBRARY( OSGTEXT_LIBRARY syzText )
FINDLIBRARY( OSGTEXT_LIBRARY_DEBUG syzTextd )
FINDLIBRARY( OSGUTIL_LIBRARY syzUtil )
FINDLIBRARY( OSGUTIL_LIBRARY_DEBUG syzUtild )
FINDLIBRARY( OSGVIEWER_LIBRARY syzViewer )
FINDLIBRARY( OSGVIEWER_LIBRARY_DEBUG syzViewerd )
FINDLIBRARY( OSGANIMATION_LIBRARY syzAnimation )
FINDLIBRARY( OSGANIMATION_LIBRARY_DEBUG syzAnimationd )
FINDLIBRARY( OPENTHREADS_LIBRARY OpenThreads )
FINDLIBRARY( OPENTHREADS_LIBRARY_DEBUG OpenThreadsd )